version: '2'
services:
  p5-root:
    image: p5
    ports:
     - "3000:3000"
     - "3001:3001"
    environment:
     - ROOT_NODE=TRUE
     - TOPOLOGY_SERVER=p5-topology.herokuapp.com
     - RECEIVE_PORT=3000
     - JOIN_PORT=3001
     - SEND_PORT=4000
     - WAIT_CONN=0
  p5-join1:
    image: p5
    ports:
      - "3002:3002"
      - "3003:3003"
    depends_on:
      - "p5-root"
    environment:
     - ROOT_NODE=FALSE
     - RECEIVE_PORT=3002
     - SEND_PORT=4001
     - JOIN_PORT=3003
     - WAIT_CONN=6
  p5-join2:
    image: p5
    ports:
      - "3004:3004"
      - "3005:3005"
    depends_on:
      - "p5-root"
    environment:
     - ROOT_NODE=FALSE
     - RECEIVE_PORT=3004
     - SEND_PORT=4002
     - JOIN_PORT=3005
     - WAIT_CONN=12
  p5-join3:
    image: p5
    ports:
      - "3006:3006"
      - "3007:3007"
    depends_on:
      - "p5-root"
    environment:
     - ROOT_NODE=FALSE
     - RECEIVE_PORT=3006
     - SEND_PORT=4003
     - JOIN_PORT=3007
     - WAIT_CONN=18
  p5-join4:
    image: p5
    ports:
      - "3008:3008"
      - "3009:3009"
    depends_on:
      - "p5-root"
    environment:
     - ROOT_NODE=FALSE
     - RECEIVE_PORT=3008
     - SEND_PORT=4004
     - JOIN_PORT=3009
     - WAIT_CONN=24
  p5-join5:
    image: p5
    ports:
      - "3010:3010"
      - "3011:3011"
    depends_on:
      - "p5-root"
    environment:
     - ROOT_NODE=FALSE
     - RECEIVE_PORT=3010
     - SEND_PORT=4005
     - JOIN_PORT=3011
     - WAIT_CONN=30
  p5-join6:
    image: p5
    ports:
      - "3012:3012"
      - "3013:3013"
    depends_on:
      - "p5-root"
    environment:
     - ROOT_NODE=FALSE
     - RECEIVE_PORT=3012
     - SEND_PORT=4006
     - JOIN_PORT=3013
     - WAIT_CONN=36
  p5-join7:
    image: p5
    ports:
      - "3014:3014"
      - "3015:3015"
    depends_on:
      - "p5-root"
    environment:
     - ROOT_NODE=FALSE
     - RECEIVE_PORT=3014
     - SEND_PORT=4007
     - JOIN_PORT=3015
     - WAIT_CONN=42
  p5-join8:
    image: p5
    ports:
      - "3016:3016"
      - "3017:3017"
    depends_on:
      - "p5-root"
    environment:
     - ROOT_NODE=FALSE
     - RECEIVE_PORT=3016
     - SEND_PORT=4008
     - JOIN_PORT=3017
     - WAIT_CONN=48
  p5-join9:
    image: p5
    ports:
      - "3018:3018"
      - "3019:3019"
    depends_on:
      - "p5-root"
    environment:
     - ROOT_NODE=FALSE
     - RECEIVE_PORT=3018
     - SEND_PORT=4009
     - JOIN_PORT=3019
     - WAIT_CONN=54
  p5-join10:
    image: p5
    ports:
      - "3020:3020"
      - "3021:3021"
    depends_on:
      - "p5-root"
    environment:
     - ROOT_NODE=FALSE
     - RECEIVE_PORT=3020
     - SEND_PORT=4010
     - JOIN_PORT=3021
     - WAIT_CONN=60